# template of an environment file for conda
# update as needed

# To create the environment please run in powershell:
# conda env create -f environment.yaml

# Update your packages by running this in powershell:
# conda env update --file environment.yaml --prune

# OBS also run this line to install the local package (include the dot)
# pip install -e .

# To activate the environment, run:
# conda activate gurobi-opt
# or use the python interpreter selection menu in VS Code

# To add new packages, add them to the environment.yaml file and run the update command above.
# Check for available version using "pip index versions package-name"

name: gurobi-opt
channels:
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - python=3.11
  - gurobi            # gurobi + gurobipy from the official channel
  - numpy>=1.26
  - pandas>=2.1
  - matplotlib>=3.8
  - seaborn>=0.13
  - jupyterlab>=4.2
  - ipykernel>=6.29
  - xarray>=2025.9
  - pip
  - pip:
      - plotly>=5.22
      - tqdm>=4.66



# To install gurobi, enter the following command in the terminal:
#conda install -c gurobi gurobi
# You will need a Gurobi license to use the solver. Please visit https://www.gurobi.com/downloads/end-user-license-agreement-academic/ to get a free academic license.